# name属性用来指定这个工作流的名字

name: CI
env:
  TZ: Asia/Shanghai

# 这个部分用来指定能够触发工作流执行的事
on:
  # 当对分支master进行push操作的时候，这个工作流就被触发了
  schedule:
    - cron: '*/5 * * * *'

  # 允许你手动在Github网页上执行该workflow
  workflow_dispatch:

# 一个workflow可以由多个job组成，可以并行或者分离运行，在jobs里面来说明要交给Github action执行的任务
jobs:
  # 这个jobs中的一个任务，名字叫做build（任务的名字是自己取的）
  build:
    env:
      TZ: Asia/Shanghai
    # 用来指定这个任务在什么操作系统上面跑，此处运行在最新版本的ubuntu镜像上（服务器是Github免费提供的）
    runs-on: ubuntu-latest

    # 指出这个build任务的步骤
    steps:
      # 将你的job指向你的文件目录$GITHUB_WORKSPACE，用来运行你的脚本
      - name: checkout
      - uses: actions/checkout@v3

      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install requirements
        run: |
         python3 -m pip install --upgrade pip

